FROM docker.io/library/python:3.13-alpine
WORKDIR /app
COPY app.py .
RUN mkdir /data && chown 10001:10001 /data
USER 10001:10001
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
CMD ["python", "app.py"]
