[platformio]
default_envs = esp32dev

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts = pre:load_env.py
lib_deps = 
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.9
    bblanchon/ArduinoJson@^6.21.3

[env:esp32dev]
custom_env_file = .env

[env:inside]
custom_env_file = .env.inside

[env:outside]
custom_env_file = .env.outside
